export const mockVehicles = [
  {
    id: 1,
    plate: 'RNT-4A21',
    model: 'Onix Plus',
    brand: 'Chevrolet',
    year: '2024',
    dailyRate: '189.90',
    category: 'Sedan',
    status: 'Disponivel',
  },
  {
    id: 2,
    plate: 'QPX-8B19',
    model: 'HB20',
    brand: 'Hyundai',
    year: '2023',
    dailyRate: '169.90',
    category: 'Hatch',
    status: 'Locado',
  },
  {
    id: 3,
    plate: 'SUL-2C77',
    model: 'T-Cross',
    brand: 'Volkswagen',
    year: '2025',
    dailyRate: '279.90',
    category: 'SUV',
    status: 'Disponivel',
  },
  {
    id: 4,
    plate: 'BRM-9D35',
    model: 'Corolla',
    brand: 'Toyota',
    year: '2024',
    dailyRate: '299.90',
    category: 'Sedan premium',
    status: 'Manutencao',
  },
  {
    id: 5,
    plate: 'KAR-6E10',
    model: 'Strada',
    brand: 'Fiat',
    year: '2023',
    dailyRate: '229.90',
    category: 'Utilitario',
    status: 'Disponivel',
  },
]
